[package]
name = "resume-soup"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Hunter Coles"]
license = "MIT"
description = "A minimal and fully-customizable CV template (forked from chi-cv-template)."
repository = "https://github.com/HunterColes/resume_soup"
keywords = ["cv", "resume"]
categories = ["cv"]

[template]
path = "template"
entrypoint = "resume.typ"
thumbnail = "resume.png"
